In [1]:
# 데이터 구성:Series, DataFrame
import pandas as pd
# 데이터 시각화
import matplotlib.pyplot as plt
import matplotlib

import seaborn as sns

# 데이터 scaling
from sklearn.preprocessing import StandardScaler
# 데이터 분할:train, test
from sklearn.model_selection import train_test_split

# 분류 Decision Tree
from sklearn.tree import DecisionTreeClassifier
# 분류 Random Forest
from sklearn.ensemble import RandomForestClassifier
# 분류 Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
# 분류 NN (MLPClassifier)
from sklearn.neural_network import MLPClassifier
# 분류 SVM
from sklearn.svm import SVC
# 실행결과 경고메시지 출력 제외
import warnings

warnings.filterwarnings('ignore')
# 모델 성능 평가: Precision, Recall, F1 Score, ROC Curve, AUC
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc
from sklearn.metrics import confusion_matrix, classification_report

# Check the Frequency of Variable
from collections import Counter
# 그래프 한글폰트 적용:맑은 고딕
matplotlib.rc("font", family = "NanumGothic")
# 그래프 (-) 기호 표시
matplotlib.rc("axes", unicode_minus = False)

데이터 불러오는 작업

In [2]:
df_raw = pd.read_csv('/home/piai/반도체 데이터 분석/Final2_data.csv')
df_operation = pd.read_csv('/home/piai/반도체 데이터 분석/최적운전조건.csv')

In [3]:
df_raw

,No_Die,Ox_Chamber,type,Temp_OXid,ppm,Pressure,Oxid_time,thickness,Lot_Num,Wafer_Num,...,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Target,Error_message,Target_error,Path
0,NOLSM32513132,2,0,1214.33,26.78,0.30,120,712.98,13,28,...,3.010000e+17,6.000000e+17,30795.856,103.513,854,154,141,none,0,21111
1,NOLSM32513133,2,0,977.98,30.90,0.14,137,714.41,13,29,...,3.030000e+17,6.000000e+17,32135.659,105.628,895,156,55,none,0,21122
2,NOLSM32513134,2,0,1175.95,31.11,0.25,116,710.27,13,30,...,2.980000e+17,6.000000e+17,31057.876,102.716,898,152,96,none,0,21133
3,NOLSM32513135,2,0,933.47,31.20,0.29,143,710.62,13,31,...,3.000000e+17,6.000000e+17,32140.435,102.902,879,155,105,none,0,21111
4,NOLSM32513136,2,0,1140.60,31.38,0.20,76,711.70,13,32,...,3.020000e+17,6.000000e+17,31985.989,101.465,882,155,79,none,0,21122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14417,NOLSM32528517,3,0,1119.37,27.37,0.13,50,711.92,13,23,...,3.000000e+17,6.000000e+17,31877.793,101.566,914,155,134,none,0,32222
14418,NOLSM32528518,3,0,1263.81,31.62,0.18,112,696.98,13,24,...,3.000000e+17,6.000000e+17,30107.476,102.856,899,156,129,none,0,32311
14419,NOLSM32528519,3,0,964.04,38.56,0.08,78,706.11,13,25,...,2.990000e+17,6.000000e+17,32048.298,102.541,903,157,78,none,0,33111
14420,NOLSM32528520,3,0,1058.80,32.84,0.38,80,707.33,13,26,...,3.000000e+17,6.000000e+17,31221.150,104.359,879,155,60,none,0,33222
14421,NOLSM32528521,3,0,1046.03,44.90,0.31,89,715.99,13,27,...,3.000000e+17,6.000000e+17,31645.170,100.492,890,157,74,none,0,33333

In [4]:
df_operation

,No_Die,Ox_Chamber,type,Temp_OXid,ppm,Pressure,Oxid_time,thickness,Lot_Num,Wafer_Num,...,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Target,Error_message,Target_error,Path
0,NOLSM32513132,2,0,1299.513457,49.898176,0.30,238.539608,712.98,13,28,...,3.010000e+17,6.000000e+17,30795.856,99.205607,854.000000,149.781240,141,none,0,21111
1,NOLSM32513133,2,0,1299.945563,49.393038,0.14,9.436692,714.41,13,29,...,3.030000e+17,6.000000e+17,32135.659,98.877620,856.567280,149.824093,55,none,0,21122
2,NOLSM32513134,2,0,865.426666,49.661995,0.25,240.783984,710.27,13,30,...,2.980000e+17,6.000000e+17,31057.876,99.746066,860.554481,149.648712,96,none,0,21133
3,NOLSM32513135,2,0,863.295511,49.989409,0.29,14.794226,710.62,13,31,...,3.000000e+17,6.000000e+17,32140.435,99.961511,859.750307,149.143083,105,none,0,21111
4,NOLSM32513136,2,0,867.366408,46.822278,0.20,235.439528,711.70,13,32,...,3.020000e+17,6.000000e+17,31985.989,107.218360,939.017947,149.176037,79,none,0,21122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14417,NOLSM32528517,3,0,1306.357828,49.727677,0.13,16.249642,711.92,13,23,...,3.000000e+17,6.000000e+17,31877.793,107.382932,856.295623,149.177147,134,none,0,32222
14418,NOLSM32528518,3,0,1295.006681,21.775398,0.18,235.092449,696.98,13,24,...,3.000000e+17,6.000000e+17,30107.476,99.859421,854.518208,149.474819,129,none,0,32311
14419,NOLSM32528519,3,0,866.688902,21.451544,0.08,239.101096,706.11,13,25,...,2.990000e+17,6.000000e+17,32048.298,99.445429,941.058751,149.844846,78,none,0,33111
14420,NOLSM32528520,3,0,866.964508,21.692065,0.38,12.117791,707.33,13,26,...,3.000000e+17,6.000000e+17,31221.150,106.976636,932.328127,149.293191,60,none,0,33222
14421,NOLSM32528521,3,0,870.310513,21.146215,0.31,14.890576,715.99,13,27,...,3.000000e+17,6.000000e+17,31645.170,107.399796,940.607977,149.239036,74,none,0,33333

In [5]:
df_raw.columns

Index(['No_Die', 'Ox_Chamber', 'type', 'Temp_OXid', 'ppm', 'Pressure',
       'Oxid_time', 'thickness', 'Lot_Num', 'Wafer_Num', 'Datetime',
       'photo_soft_Chamber', 'resist_target', 'N2_HMDS', 'pressure_HMDS',
       'temp_HMDS', 'temp_HMDS_bake', 'time_HMDS_bake', 'spin1', 'spin2',
       'spin3', 'photoresist_bake', 'temp_softbake', 'time_softbake',
       'lithography_Chamber', 'Line_CD', 'Wavelength', 'Resolution',
       'Energy_Exposure', 'Etching_Chamber', 'Thin F4', 'Thin F3', 'Thin F2',
       'Thin F1', 'Temp_Etching', 'Source_Power', 'Selectivity', 'Chamber_Num',
       'Flux60s', 'Flux90s', 'Flux160s', 'Flux480s', 'Flux840s',
       'input_Energy', 'Temp_implantation', 'Furance_Temp', 'RTA_Temp',
       'Target', 'Error_message', 'Target_error', 'Path'],
      dtype='object')

### 모델 학습

In [8]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

df_raw = df_raw.drop(columns=['No_Die', 'Ox_Chamber', 'Lot_Num', 'Wafer_Num',
                              'Datetime', 'photo_soft_Chamber','lithography_Chamber','Etching_Chamber','Chamber_Num',
                              'Target', 'Error_message', 'Path'], errors='ignore')

# 불량률 예측 모델 학습
X = df_raw.drop(columns=['Target_error'])
y = df_raw['Target_error']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4321)

In [23]:
rf_model = RandomForestClassifier(random_state=12,n_estimators = 100,max_depth = 5)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_train)
print("Classification Report:\n", classification_report(y_train, y_pred))
# Evaluate on the test set
y_pred = rf_model.predict(X_test)
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98      9547
           1       1.00      0.21      0.35       548

    accuracy                           0.96     10095
   macro avg       0.98      0.61      0.66     10095
weighted avg       0.96      0.96      0.94     10095

Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98      4095
           1       1.00      0.18      0.31       232

    accuracy                           0.96      4327
   macro avg       0.98      0.59      0.64      4327
weighted avg       0.96      0.96      0.94      4327

In [17]:
rf_model = DecisionTreeClassifier(random_state=4321)
rf_model.fit(X_train, y_train)
# Evaluate on the test set
y_pred = rf_model.predict(X_test)
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      5460
           1       1.00      0.98      0.99       309

    accuracy                           1.00      5769
   macro avg       1.00      0.99      0.99      5769
weighted avg       1.00      1.00      1.00      5769

In [18]:
rf_model.feature_importances_

array([0.        , 0.16176453, 0.05391071, 0.        , 0.        ,
       0.01452468, 0.        , 0.04659986, 0.00213844, 0.        ,
       0.00416996, 0.        , 0.        , 0.00430772, 0.01293328,
       0.        , 0.00702773, 0.        , 0.0496306 , 0.00406304,
       0.01709523, 0.03226537, 0.15938937, 0.03702718, 0.06046989,
       0.00648348, 0.        , 0.0329692 , 0.        , 0.025003  ,
       0.09135891, 0.01249373, 0.        , 0.        , 0.02691768,
       0.02896039, 0.02669236, 0.08180367])

In [15]:
df_raw['Target_error'].value_counts()

0    13642
1      780
Name: Target_error, dtype: int64